# Generated by Django 4.0.6 on 2022-07-06 10:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('amount_options', models.IntegerField(help_text='Plan should be of atleast Rs 1/-', validators=[django.core.validators.MinValueValidator(1)])),
                ('tenure_options', models.CharField(choices=[('1 Months', '1 Months'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('1 Year', '1 Year')], max_length=8)),
                ('benefit_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('benefit_type', models.CharField(choices=[('Cashback', 'Cashback'), ('ExtraVoucher', 'ExtraVoucher')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_name', models.CharField(max_length=200)),
                ('promo_type', models.CharField(choices=[('Users', 'By The Number Of Users'), ('Time Period', 'By A Time Period')], max_length=23)),
                ('description', models.TextField(blank=True, null=True)),
                ('promo_start', models.DateField(blank=True, null=True)),
                ('promo_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_prm.plan')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashback_amount', models.FloatField(blank=True, null=True)),
                ('enrolled_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_prm.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
