# Generated by Django 4.0.6 on 2022-07-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergoals',
            name='selected_promo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_prm.promotion'),
            preserve_default=False,
        ),
    ]
