# Generated by Django 4.0.6 on 2022-07-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prm', '0002_customergoals_selected_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergoals',
            name='cashback_amount',
            field=models.FloatField(blank=True, help_text='Total Cashback Amount Based On Benefit Percentage Of Plan', null=True),
        ),
    ]
