# Generated by Django 4.0.6 on 2022-07-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prm', '0003_alter_customergoals_cashback_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergoals',
            name='is_customer_plan_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customergoals',
            name='is_payment_recieved',
            field=models.BooleanField(default=False),
        ),
    ]
