# Generated by Django 4.0.6 on 2022-07-06 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prm', '0004_customergoals_is_customer_plan_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='benefit_percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
