# Generated by Django 4.0.6 on 2022-07-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prm', '0005_alter_plan_benefit_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promo_type',
            field=models.CharField(choices=[('By The Number Of Users', 'By The Number Of Users'), ('By A Time Period', 'By A Time Period')], max_length=23),
        ),
    ]
