# Generated by Django 4.0.6 on 2022-07-08 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prm', '0006_alter_promotion_promo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergoals',
            name='enrolled_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_prm.plan'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_type',
            field=models.CharField(choices=[('by_the_number_of_users', 'by_the_number_of_users'), ('by_a_time_period', 'by_a_time_period')], max_length=23),
        ),
    ]
